In [1]:
from huggingface_hub import login
token = "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"
login(token=token)

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
Your token has been saved to /home/gildenbj/.cache/huggingface/token
Login successful


In [3]:
import joblib
cluster_model = joblib.load("/gstore/data/dp_labs/tcga/1000_per_slide/embeddings/_uni/5239_m_10_0_tile_256_step_256_mask_atd_image_format_png_NONE_embed_imagenet_backbone_backbone_uni_model_name_uni_aug_0_stain_None/aggregated/clusters_model_128.joblib")

(128, 1024)


In [2]:
import numpy as np
import matplotlib.pyplot as plt
import importlib
import dff_seg.dff_seg
importlib.reload(dff_seg.dff_seg)
from dff_seg.dff_seg import DFFSeg, show_segmentation_on_image
import numpy as np
from PIL import Image
from pytorch_grad_cam.utils.image import preprocess_image
from torchvision.models import resnet50
from functools import partial
import torch
import cv2
import timm
import math
import joblib

cluster_model = joblib.load("/gstore/data/dp_labs/tcga/1000_per_slide/embeddings/_uni/5239_m_10_0_tile_256_step_256_mask_atd_image_format_png_NONE_embed_imagenet_backbone_backbone_uni_model_name_uni_aug_0_stain_None/aggregated/clusters_model_32.joblib")

def pad_divisible(img: np.ndarray, number: int = 16) -> np.ndarray:
    """
    Pad the image shape to be a multiple of number

    :param img: Input image.
    :param scale: Scale factor.
    :return: Padded input image.
    """
    w = number * math.ceil(img.shape[1] / number) - img.shape[1]
    h = number * math.ceil(img.shape[0] / number) - img.shape[0]

    if w > 0 or h > 0:
        padded = cv2.copyMakeBorder(
            img, 0, h, 0, w, borderType=cv2.BORDER_REPLICATE)
        return padded
    else:
        return img


class TransformerReshapeTransform:
    def __init__(self):
        self.input_tensor_shape = None

    def __call__(self, tensor):
        print(self.input_tensor_shape)
        result = torch.nn.ReLU()(tensor[:, 1:, :].reshape(tensor.size(0),
                                self.input_tensor_shape[2] // 16,
                                self.input_tensor_shape[3] // 16,
                                tensor.size(2)))
        # Bring the channels to the first dimension,
        # like in CNNs.
        result = result.transpose(2, 3).transpose(1, 2)
        return result

print(cluster_model.cluster_centers_.shape)

img_path = r"/home/gildenbj/a.png"
img = np.array(Image.open(img_path))
orig_shape = img.shape
img = pad_divisible(img)
rgb_img_float = np.float32(img) / 255
input_tensor = preprocess_image(rgb_img_float,
                                mean=[0.485, 0.456, 0.406],
                                std=[0.229, 0.224, 0.225])

img_path2 = r"/home/gildenbj/b.png"
img2 = np.array(Image.open(img_path2))
orig_shape2 = img2.shape
img2 = pad_divisible(img2)

rgb_img_float2 = np.float32(img2) / 255
input_tensor2 = preprocess_image(rgb_img_float2,
                                mean=[0.485, 0.456, 0.406],
                                std=[0.229, 0.224, 0.225])



model_name = "uni"

if model_name == "gigapath":
    model = timm.create_model("hf_hub:prov-gigapath/prov-gigapath", pretrained=True, dynamic_img_size=True)
    target_layer = model.blocks[-1]
    transform = TransformerReshapeTransform()

if model_name == "resnet50":
    concepts = np.load("/home/gildenbj/dev/dff_seg/concepts_resnet50_concepts.npy")
    model = resnet50(pretrained=True)
    target_layer = model.layer4
    transform = None
elif model_name == "uni":
    model = timm.create_model("hf-hub:MahmoodLab/uni", pretrained=True, init_values=1e-5, dynamic_img_size=True)
    target_layer = model.blocks[-1]    
    transform = TransformerReshapeTransform()

model.eval()

unsupervised_seg = DFFSeg(
    model=model,
    target_layer=target_layer,
    reshape_transform=transform,
    scale_before_argmax=True
)

unsupervised_seg.reshape_transform.input_tensor_shape = input_tensor.shape
concepts = cluster_model.cluster_centers_
concepts[concepts < 0] = 0
print(concepts)
print(concepts.min(), concepts.max())
segmentation = unsupervised_seg.predict_project_concepts(input_tensor, concepts)
visualization = show_segmentation_on_image(
    img=img,
    segmentation=segmentation,
    image_weight=0.7,
    n_categories=len(concepts))

unsupervised_seg.reshape_transform.input_tensor_shape = input_tensor2.shape
segmentation2 = unsupervised_seg.predict_project_concepts(input_tensor2, concepts)
visualization2 = show_segmentation_on_image(
    img=img2,
    segmentation=segmentation2,
    image_weight=0.7,
    n_categories=len(concepts))

visualization = visualization[:orig_shape[0], :orig_shape[1], :]
visualization2 = visualization2[:orig_shape2[0], :orig_shape2[1], :]

display(Image.fromarray(visualization))
display(Image.fromarray(visualization2))



(32, 1024)
[[0.17423524 0.38282013 0.16792561 ... 0.23269433 0.3017246  0.12458277]
 [0.18642387 0.28968507 0.16978127 ... 0.25196546 0.26143107 0.11726301]
 [0.16904913 0.28885865 0.15911302 ... 0.18029368 0.22724226 0.10550998]
 ...
 [0.18573405 0.13777147 0.1582502  ... 0.16789979 0.24432997 0.09890669]
 [0.03561661 0.2147832  0.05925214 ... 0.09241623 0.11835353 0.02232988]
 [0.15493439 0.18456897 0.17777306 ... 0.17943795 0.2152016  0.1111009 ]]
-5.3326232e-12 4.3461933
torch.Size([1, 3, 1024, 1440])
(1, 64, 90, 1024) (5760, 1024) (32, 1024)


ValueError: Negative values in data passed to NMF (input H)